<a href="https://colab.research.google.com/github/myumbla3/AI_Assignment_04/blob/main/assi4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/github/myumbla3/AI_Assignment_04/blob/main/assi4.ipynb#scrollTo=BApy8gtzm0UU

 <a href="https://github.com/myumbla3/AI_Assignment_04/blob/main/assi4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#imports
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part1: Load the dataset

In [ ]:
# load Iris data set

iris_data = load_iris()
iris_df = pd.DataFrame(
  data=np.append(
    iris_data['data'], 
    np.array(iris_data['target']).reshape(len(iris_data['target']), 1), 
    axis=1),
  columns=np.append(iris_data['feature_names'], ['species'])
)

iris_df['species'] = iris_df['species'].astype('int64')

iris_df.sample(n=15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
147                6.5               3.0                5.2               2.0   
130                7.4               2.8                6.1               1.9   
28                 5.2               3.4                1.4               0.2   
64                 5.6               2.9                3.6               1.3   
80                 5.5               2.4                3.8               1.1   
100                6.3               3.3                6.0               2.5   
18                 5.7               3.8                1.7               0.3   
144                6.7               3.3                5.7               2.5   
65                 6.7               3.1                4.4               1.4   
11                 4.8               3.4                1.6               0.2   
99                 5.7               2.8                4.1               1.3   
140                6.7               3.1                5.6               2.4   
14                 5.8               4.0                1.2               0.2   
23                 5.1               3.3                1.7               0.5   
79                 5.7               2.6                3.5               1.0   

     species  
147        2  
130        2  
28         0  
64         1  
80         1  
100        2  
18         0  
144        2  
65         1  
11         0  
99         1  
140        2  
14         0  
23         0  
79         1

In [ ]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

My features are the length, width of sepals and petals and my labels or target is the species of the irs setosa, versicolour, and virginica. I made my labels be displayed as 0, 1, 2 rather than there names.

# Part 2: Split the dataset into train and test

In [ ]:
x=iris_data.data
y=iris_data.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=1)

# Part 3: Logistic Regression 

In [ ]:
#Use sklearn to train a LogisticRegression model on the training set
LR=LogisticRegression()

lrmodel =LR.fit(x_train, y_train)

# Create a sample datapoint and predict the output of that sample with the trained model
predictions=lrmodel.predict_proba(np.array([[1,2,3,4]]))
predictions

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[0.05188112, 0.00542333, 0.94269555]])

In [ ]:
#Report on the score for that model, in your own words (markdown, not code) explain what the score means
print(f"Score: {lrmodel.score(x_test,y_test)}")

Score: 1.0


This score gives the predicted score of a given event using the logistic regression. SO it gives the testing accuracy.

In [ ]:
#Extract the coefficents and intercepts for the boundary line(s)
LR.coef_,LR.intercept_

(array([[-0.42517641,  0.88010144, -2.460077  , -0.99830141],
        [ 0.53888286, -0.32756661, -0.17158846, -0.95440952],
        [-0.11370646, -0.55253484,  2.63166547,  1.95271093]]),
 array([  9.82456237,   1.97656097, -11.80112334]))

# Part 4: Support Vector Machine

In [ ]:
#Use sklearn to train a Support Vector Classifier on the training set
svmmodel = svm.SVC(probability =True).fit(x_train, y_train)
#For a sample datapoint, predict the probabilities for each possible class
predict=svmmodel.predict_proba(np.array([[1,2,3,4]]))
predict

array([[0.2454599 , 0.27871636, 0.47582374]])

In [ ]:
print(f"Score: {svmmodel.score(x_test,y_test)}")

Score: 1.0


Report on the score for the SVM, what does the score measure?
The score of the svm is mesuring the mean accuracy on the iris test data and labels. 

# Part 5: Neural Network

In [ ]:
#Use sklearn to train a Neural Network (MLP Classifier) on the training set
nn = MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(5,2), 
                    random_state=1)

nnmodel=nn.fit(x_train, y_train)  
#For a sample datapoint, predict the probabilities for each possible class
pred=nnmodel.predict_proba(np.array([[1,2,3,4]]))
pred

array([[0.34733839, 0.32906164, 0.32359997]])

In [ ]:
print(f"Score: {nnmodel.score(x_test,y_test)}")

Score: 0.26666666666666666


Report on the score for the Neural Network, what does the score measure?
The score here is returning the accuracy of the iris data set and labels.

In [ ]:
#Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)
nnc = MLPClassifier(solver='lbfgs', 
                    alpha=1e-5,
                    hidden_layer_sizes=(15,), 
                    random_state=1)

nnmodelc=nnc.fit(x_train, y_train)
print(f"Score: {nnmodelc.score(x_test,y_test)}")

Score: 1.0


By changing the hidden layer size to 15 the accuracy drastically improved from .2666 to 1.0

# Part 6: K-Nearest Neighbors

In [ ]:
#Use sklearn to 'train' a k-Neighbors Classifier
#Note: KNN is a nonparametric model and technically doesn't require training
#fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
KN = KNeighborsClassifier()
knmodel=KN.fit(x_train, y_train)

#For a sample datapoint, predict the probabilities for each possible class
prediction=knmodel.predict_proba(np.array([[1,2,3,4]]))
prediction

array([[0. , 0.8, 0.2]])

In [ ]:
print(f"Score: {knmodel.score(x_test,y_test)}")

Score: 1.0


Report on the score for kNN, what does the score measure?
The score for the kNN is the coefficient of determination of the prediction made from the iris test data.

# Part 7: Conclusions and takeaways
In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise

Overall, the results were mostly 1 for the different models score. Which makes most of them perform well like KNN, logistic regression and the svc with a rgb kernel. I was surprised that the NN had the worst result and with just changing the hidden layer size it changed its score drastically. 